# This action works transparently on both Blacksmith and GitHub-hosted runners.
# Blacksmith runners benefit from transparent caching and optional Docker layer caching.
# GitHub-hosted runners use standard GitHub Actions caching.

name: 'Node.js Build Setup'
description: 'Configures Node.js with pnpm, installs dependencies, enables Turborepo caching, and builds the project.'

inputs:
  node-version:
    description: 'Node.js version to use. Uses latest 22.x by default.'
    required: false
    default: '22.x'
  enable-docker-cache:
    description: 'Skipped - Docker cache setup (Blacksmith only)'
    required: false
    default: 'false'
    type: boolean
  build-command:
    description: 'Command to execute for building the project.'
    required: false
    default: 'pnpm build'
    type: string

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install Dependencies
      run: |
        pnpm install --frozen-lockfile
      shell: bash

    - name: Configure Turborepo Cache
      uses: rharkor/caching-for-turbo@v2.3.5

    - name: Setup Docker Builder
      if: ${{ inputs.enable-docker-cache == 'true' }}
      uses: docker/setup-buildx-action@v3

    - name: Build Project
      if: ${{ inputs.build-command != '' }}
      run: ${{ inputs.build-command }}
      shell: bash
      env:
        NODE_OPTIONS: '--max-old-space-size=6144'